name = "LanguageServer"
uuid = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
version = "1.1.0"

[deps]
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DocumentFormat = "ffa9a821-9c82-50df-894e-fbcef3ed31cd"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
StaticLint = "b3cc710f-9c33-5bdb-a03d-a94903873e97"
SymbolServer = "cf896787-08d5-524d-9de7-132aaa0cb996"
Tokenize = "0796e94c-ce3b-5d07-9a54-7f471281c624"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"

[compat]
CSTParser = "1.1"
DocumentFormat = "1.1.1"
JSON = "0.20, 0.21"
StaticLint = "1.1"
Tokenize = "0.5.7"
URIParser = "0.4.0"
julia = "1"
SymbolServer = "1.0.1"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[targets]
test = ["Test", "Sockets", "Pkg", "LibGit2", "Serialization", "SHA"]
